site_url: https://dynamic-cheesecake-5fbd8b.netlify.app/
logo_url: https://dynamic-cheesecake-5fbd8b.netlify.app/icon.png

publish_mode: editorial_workflow
backend:
  name: git-gateway
  repo: blargoflatsomen/fourshame
  branch: master
  squash_merges: true

# used together with `npx netlify-cms-proxy-server`. https://www.netlifycms.org/docs/beta-features/#working-with-a-local-git-repository
local_backend: true

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: dehtu15lz
    api_key: 539362117499135
    use_transformations: true

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
# create a File version of the Homepage and About Us page
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - label: 'Timeline'
    name: 'timeline'
    folder: 'content/timeline'
    create: true
    format: 'frontmatter'
    slug: '{{fields.createdAt}}-{{slug}}'
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - label: 'Years'
        name: 'years'
        widget: 'list'
        summary: '{{fields.year}}'
        fields:
          - { label: 'Year', name: 'year', widget: 'string', required: true }
          - {
              label: 'Era',
              name: 'era',
              widget: 'select',
              default: 'ae',
              options: [{ label: 'After Exodus', value: 'ae' }, { label: 'Before Exodus', value: 'be' }],
            }
          - { label: 'Overview', name: 'overview', widget: 'markdown', required: false }
          - label: 'Events'
            name: 'events'
            widget: 'list'
            summary: '{{fields.month}}'
            fields:
              - {
                  label: 'Month',
                  name: 'month',
                  widget: 'select',
                  default: '1',
                  options:
                    [
                      { label: 'Reborn', value: '1' },
                      { label: 'Blushing', value: '2' },
                      { label: 'Courageous', value: '3' },
                      { label: 'Aware', value: '4' },
                      { label: 'Lucky', value: '5' },
                      { label: 'Protective', value: '6' },
                      { label: 'Passionate', value: '7' },
                      { label: 'Fortunate', value: '8' },
                      { label: 'Nostalgic', value: '9' },
                      { label: 'Creative', value: '10' },
                      { label: 'Celebrant', value: '11' },
                      { label: 'Passing', value: '12' },
                    ],
                }
              - { label: 'Content', name: 'body', widget: 'markdown', required: true }
  - name: 'article'
    label: 'Article'
    folder: 'content/articles'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    # editor:
    #   preview: true
    fields:
      - { label: 'Created Date', name: 'createdAt', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          default: 'default',
          required: true,
          options:
            [
              { label: 'Default', value: 'default' },
              { label: 'Location', value: 'location' },
              { label: 'Cosmology', value: 'cosmology' },
            ],
        }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: false }
  - name: 'houseRule'
    label: 'House Rule'
    folder: 'content/houseRules'
    create: true
    format: 'frontmatter'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Content', name: 'body', widget: 'markdown', required: false }
      - label: 'Tabs'
        name: 'tabs'
        widget: 'list'
        summary: '{{fields.tabName}}'
        fields:
          - { label: 'Tab Name', name: 'tabName', widget: 'string', required: true }
          - { label: 'Content', name: 'body', widget: 'markdown', required: true }

  - name: 'character'
    label: 'Character'
    folder: 'content/characters'
    create: true
    format: 'frontmatter'
    slug: '{{fields.name}}'
    fields:
      - label: 'Character Image'
        name: 'thumbnail'
        widget: 'image'
        required: false
        choose_url: true
        media_library:
          config:
            multiple: false
            default_transformations:
              - fetch_format: auto
                width: 300    
                quality: auto
                crop: scale
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - {
          label: 'Type',
          name: 'type',
          widget: 'select',
          default: 'npc',
          options: [{ label: 'PC', value: 'pc' }, { label: 'NPC', value: 'npc' }],
        }
      - {
          label: 'Status',
          name: 'status',
          widget: 'select',
          default: 'alive',
          options:
            [
              { label: 'Alive', value: 'alive' },
              { label: 'Dead', value: 'dead' },
              { label: 'Unknown', value: 'unknown' },
            ],
        }
      - { label: 'Bio', name: 'body', widget: 'markdown', required: false }
  - name: 'player'
    label: 'Player Bio'
    folder: 'content/players'
    create: true
    format: 'frontmatter'
    slug: '{{fields.name}}'
    fields:
      - label: 'Profile Image'
        name: 'thumbnail'
        widget: 'image'
        choose_url: true
        media_library:
          config:
            multiple: true
      - { label: 'Name', name: 'name', widget: 'string', required: true }
      - { label: 'Subtitle', name: 'subtitle', widget: 'string', required: false }
      - { label: 'Bio', name: 'body', widget: 'markdown', required: false }
